// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace SWApp
{
    public partial class MLMForecasting
    {
        /// <summary>
        /// model input class for MLMForecasting.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"nakład")]
            public float Nakład { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"koszt")]
            public float Koszt { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"ilość elementów")]
            public float Ilość_elementów { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"waga")]
            public float Waga { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"jakość danych")]
            public string Jakość_danych { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"grupa")]
            public string Grupa { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"inwersja nakładu")]
            public float Inwersja_nakładu { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"wskaznik cena-ilosc")]
            public float Wskaznik_cena_ilosc { get; set; }

            [LoadColumn(8)]
            [ColumnName(@"wskaznik cena-waga")]
            public float Wskaznik_cena_waga { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLMForecasting.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"nakład")]
            public float Nakład { get; set; }

            [ColumnName(@"koszt")]
            public float Koszt { get; set; }

            [ColumnName(@"ilość elementów")]
            public float Ilość_elementów { get; set; }

            [ColumnName(@"waga")]
            public float Waga { get; set; }

            [ColumnName(@"jakość danych")]
            public float[] Jakość_danych { get; set; }

            [ColumnName(@"grupa")]
            public float[] Grupa { get; set; }

            [ColumnName(@"inwersja nakładu")]
            public float Inwersja_nakładu { get; set; }

            [ColumnName(@"wskaznik cena-ilosc")]
            public float Wskaznik_cena_ilosc { get; set; }

            [ColumnName(@"wskaznik cena-waga")]
            public float Wskaznik_cena_waga { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLMForecasting.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
